# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  timeFormat: 2006-Jan-02
  fileTreeSortOrder: foldersFirst
  nerdFontsVersion: 3

